Fix vcpkg error due to missing mandatory field
As per [1] `builtin-baseline` is a mandatory field for a top-level
project like this one.  Missing this out leads to an error in VS 2022
Developer Command Prompt:

> error: this vcpkg instance requires a manifest with a specified
> baseline in order to interact with ports.

[1]: https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-configuration-json

Choose 2022 Jul 1 commit as baseline as it succeeds last commit but
not years ahead of it.